"""empty message

Revision ID: 807f0298c846
Revises: 
Create Date: 2024-04-26 14:47:31.694031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '807f0298c846'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toyrental',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('toyname', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('components', sa.String(), nullable=True),
    sa.Column('explain', sa.String(), nullable=True),
    sa.Column('rental', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('number'),
    sa.UniqueConstraint('components')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toyrental')
    # ### end Alembic commands ###
